version: '4.30.0'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        environment:
            NODE_ENV: production
            API_URL: https://api.example.com
            PORT: 3001
        volumes:
            - .:/app
            - /app/node_modules
