name: Deploy to VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Deploy to VPS
              uses: appleboy/ssh-action@v0.1.5
              with:
                  host: ${{ secrets.VPS_IP }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  port: ${{ secrets.VPS_PORT }}
                  script: |
                      if [ ! -d "/image/.git" ]; then
                        git clone https://github.com/Pa3eAnnee/webapp.git /image
                      else
                        cd /image
                        git pull origin main
                        fi
                      cd /image
                      npm install
                      npm run build
                      docker compose up -d
