name: Deploy to VPS

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: baguette42/webapp:latest

    deploy:
        runs-on: ubuntu-latest
        needs: build
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          - name: Install SSH Client
            run: sudo apt-get install -y sshpass
    
          - name: Deploy to VPS
            env:
              VPS_USER: ${{ secrets.VPS_USER }}
              VPS_IP: ${{ secrets.VPS_IP }}
              VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
            run: |
              sshpass -p $VPS_PASSWORD ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << 'EOF'
                docker pull your-dockerhub-username/your-image-name:latest
                docker stop myapp || true
                docker rm myapp || true
                docker run -d --name myapp -p 80:3001 baguette42/webapp:latest
              EOF
